### ISSUE TITLE
Feature Request(s)

### ISSUE THREAD

**Issue by ivikash** [smarlhens/python-boilerplate#101]
Hello Samuel, 

I'd like request a few features. Please let me know if this is aligned with your goals for this project

- [ ] Setup Docker devcontainers
- [ ] Include VSCode extensions in the devcontainers for easy jump start
- [ ] Include DB like postgresql
- [ ] Include FastAPI example with Database
- [ ] Guides for deployment to AWS, Azure and GCP (a true multi cloud setup) 
- [ ] Setup multiple stages - Dev, Staging, Canaray, Production
- [ ] Include a message queue like Kafka or NATS-io
- [ ] Include Redis

**Comment by smarlhens** [comment]
Hi @ivikash 👋🏻 

I hope you are well.

I apologize for the delay in responding to your feature request.

Thanks for your detailed feedback. I appreciate you taking the time to provide such specific suggestions.

While I understand the value of these additions, I'm aiming to keep the boilerplate as streamlined and minimal as possible to serve as a strong foundation for various projects.

I encourage you to fork the repository and customize it to fit your specific needs. This will allow you to experiment with the features you mentioned without affecting the core boilerplate.

I'm open to pull requests for bug fixes or minor enhancements.

Thanks for your understanding!

I wish you a great day ☀️
