### ISSUE TITLE
Feature Requests 🎉 and Open Questions 🤔

### ISSUE THREAD

**Issue by ivikash** [smarlhens/python-boilerplate#96]
Hello Samuel,

Thank you for creating this Python boilerplate repo. It's a solid starting point, and I have a few of feature requests / open questions:

1. **mypy.ini** - I am on VSCode and `pyproject.toml` gives an error - "Additional properties are not allowed ('mypy' was unexpected)". Can we move this to a separate file - `mypy.ini` instead?
2. **src/myapplication** - I was hoping to understand your preference for the src/myapplication structure rather than having a single folder such as src or myapplication.
3. Can we make the Author Name, Email, application name. configurable (or create a script) to auto-update `pyproject.toml`, `LICENSE`, and other references?
4. Setup docker and poetry commands as modules with one external dependency for example like loguru.

These adjustments would streamline usability and maintenance. Looking forward to your thoughts on these suggestions.

**Comment by smarlhens** [comment]
Hi 👋🏻 

Thank you for this issue and for your questions! I'll try to answer them as best I can.

1. There's a problem in the `pyproject.toml` file that I'll fix as soon as possible! I prefer not to have another config file (like `mypy.ini`) next to my `pyproject.toml` for greater clarity (opinionated).
2. I usually put all the source code in a `src` folder and then separate the code into modules or by domain, so I've created a placeholder folder for the boilerplate. I hope this answers your question. But I'm open to change if you think this isn't the most common practice.
3. If you know how to make these fields configurable without additional scripting, don't hesitate to send me a PR and I'll be happy to review it for you. I confess I haven't looked into whether a solution exists, I thought people using the template would replace the variables manually, but it could be useful! Thanks for the suggestion 👍🏻 
4. I'm not quite sure to follow what you're trying to achieve. Could you provide an example or create a PR with the changes you'd like to make? I'm interested in understanding how you want to do this! The idea behind this template is to reflect the most commonly used practices with Python and the latest tools.

I hope I've answered the various topics mentioned, I apologize for the delay in responding and I'm looking forward to continue discussing with you!

**Comment by ivikash** [comment]
Thank you for your response and again, Kudos to you! Great project.
